spring:
  datasource:
    username: the_tree_harvest
    password: the_tree_harvest
    url: jdbc:mysql://localhost:3306/the_tree_harvest
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: never

# For Swagger 
springdoc:
  swagger-ui:
    path: /