INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Ash', 'Fraxinus americana', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Aspen', 'Populus tremuloides', 'Pulpwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Birch', 'Betula pendula', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Black Cherry', 'Prunus serotina', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Black Oak', 'Quercus velutina', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Cedar', 'Thuja occidentalis', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Chestnut', 'Castanea dentata', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Douglas Fir', 'Pseudotsuga menziesii', 'Non-saw');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Eastern Hemlock', 'Tsuga canadensis', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Eastern White Pine', 'Pinus strobus', 'Softwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Jack Pine', 'Pinus banksiana', 'Pulpwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Lodgepole Pine', 'Pinus contorta', 'Non-saw');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Maple', 'Acer saccharinum', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Oak', 'Quercus robur', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Pine', 'Pinus longaeva', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Ponderosa Pine', 'Pinus ponderosa', 'Softwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Poplar', 'Liriodendron chinense', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Red Alder', 'Alnus rubra', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Red Maple', 'Acer rubrum', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Red Oak', 'Quercus lobatae', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Red Pine', 'Pinus resinosa', 'Pulpwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Southern Yellow Pine', 'Pinus jeffreyi', 'Softwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Spruce', 'Picea glauca', 'Softwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Subalpine Fir', 'Abies lasiocarpa', 'Xmas Trees');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Sugar Maple', 'Acer saccharum', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Sycamore', 'Platanus occidentalis', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Walnut', 'Juglans nigra', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Western Hemlock', 'Tsuga heterophylla', 'Fuelwood');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Western White Pine', 'Pinus monticola', 'Non-saw');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('White Fir', 'Abies concolor', 'Non-saw');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('White Oak', 'Quercus alba', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('White Pine', 'Pinus quinquefoliae', 'Sawtimber');
INSERT INTO tree (tree_name, tree_binomial, lumber_type) VALUES ('Yellow Poplar', 'Liriodendron tulipifera', 'Sawtimber');

